language: rust
# sudo is required to enable kcov to use the personality syscall
sudo: required
dist: trusty

matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
  include:
  - rust: nightly
    env: FEATURES="--features nightly"
  - rust: stable
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
    - cmake
    sources:
    - kalakris-cmake

cache: cargo
before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi

script:
- sudo cargo clean
- cargo build
- cargo test
- cargo test --release
branches:
  only:
  - master
  - develop
env:
  global:
  - RUST_BACKTRACE=1

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi