language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache:
  apt: true
  directories:
    - target/debug/deps
    - target/debug/build
    - target/release/deps
notifications:
  email:
    on_success: never
    on_failure: never
branches:
  only:
  - main
  - ci

script:
- cargo test --release --features index-map

env:
  global:
  - RUST_BACKTRACE=full