[package]
authors = ["Alec Embke <aembke@gmail.com>"]
description = "Structs and functions to implement the Redis protocol."
homepage = "https://github.com/aembke/redis-protocol.rs"
keywords = ["redis", "protocol", "nom", "encode", "decode"]
license = "MIT"
name = "redis-protocol"
readme = "README.md"
repository = "https://github.com/aembke/redis-protocol.rs"
version = "3.0.0"
edition = "2018"

[badges.maintenance]
status = "actively-developed"

[badges.travis-ci]
branch = "main"
repository = "aembke/redis-protocol.rs"

[dependencies]
bytes = "1"
cookie-factory = "0.3"
crc16 = "0.3"
float-cmp = "0.8"
indexmap = { version = "1.6", optional = true }
log = "0.4"
nom = "6.1"
pretty_env_logger = "0.2"

[dev-dependencies]
futures = "0.3"
lazy_static = "1.1"
rand = "0.5"

[dev-dependencies.tokio]
features = ["full"]
version = "1"

[dev-dependencies.tokio-util]
features = ["codec"]
version = "0.6"

[features]
index-map = ["indexmap"]

[lib]
doc = true
doctest = true
name = "redis_protocol"
test = true

[profile]
[profile.bench]
codegen-units = 16
debug = false
debug-assertions = false
incremental = false
opt-level = 3
overflow-checks = false
rpath = false
