[package]
authors = ["Alec Embke <aembke@gmail.com>"]
description = "Structs and functions to implement the Redis protocol."
homepage = "https://github.com/aembke/redis-protocol.rs"
keywords = ["redis", "protocol", "nom", "encode", "decode"]
license = "MIT"
name = "redis-protocol"
readme = "README.md"
repository = "https://github.com/aembke/redis-protocol.rs"
version = "1.0.0"

[badges]

[badges.maintenance]
status = "actively-developed"

[badges.travis-ci]
branch = "master"
repository = "aembke/redis-protocol.rs"

[dependencies]
bytes = "0.5"
cookie-factory = "=0.2.4"
crc16 = "0.3"
log = "0.4"
nom = "4.0"
pretty_env_logger = "0.2"

[dev-dependencies]
lazy_static = "1.1"
rand = "0.5"

[lib]
doc = true
doctest = true
name = "redis_protocol"
test = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
debug-assertions = false
codegen-units = 16
incremental = false
overflow-checks = false