[package]
authors = ["Alec Embke <aembke@gmail.com>"]
description = "Structs and functions to implement the Redis protocol."
homepage = "https://github.com/aembke/redis-protocol.rs"
keywords = ["redis", "protocol", "nom", "encode", "decode"]
license = "MIT"
name = "redis-protocol"
readme = "README.md"
repository = "https://github.com/aembke/redis-protocol.rs"
version = "3.0.2"
edition = "2018"

[badges.maintenance]
status = "actively-developed"

[badges.travis-ci]
branch = "main"
repository = "aembke/redis-protocol.rs"

[dependencies]
bytes = "1"
cookie-factory = "0.3"
crc16 = "0.4"
indexmap = { version = "1.6", optional = true }
log = "0.4"
nom = "6.1"

[dev-dependencies]
rand = "0.5"
tokio-util = { version = "0.6", features = ["codec"] }
tokio = { version = "1.12", features = ["full"] }
itertools = "0.10"

[features]
index-map = ["indexmap"]

[lib]
doc = true
doctest = true
name = "redis_protocol"
test = true

[profile]
[profile.bench]
codegen-units = 16
debug = false
debug-assertions = false
incremental = false
opt-level = 3
overflow-checks = false
rpath = false
