version: 2
jobs:
  tests-default:
    docker:
      - image: cimg/rust:1.77.0
    steps:
      - checkout
      - run:
          name: Run tests with default features
          command: cargo clean && eval `ssh-agent` && ssh-add ~/.ssh/id_rsa && cargo test --release --features "resp2 resp3 bytes codec convert"
  tests-indexmap:
    docker:
      - image: cimg/rust:1.77.0
    steps:
      - checkout
      - run:
          name: Run tests with indexmap features
          command: cargo clean && eval `ssh-agent` && ssh-add ~/.ssh/id_rsa && cargo test --release --features "index-map resp2 resp3 codec convert"
  clippy-lint:
    docker:
      - image: cimg/rust:1.77.0
    environment:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - checkout
      - run:
          name: Clippy
          command: cargo clippy --features "bytes convert codec std resp2 resp3" --lib -- -Dwarnings
  build-no-std:
    docker:
      - image: cimg/rust:1.77.0
    steps:
      - checkout
      - run:
          name: Switch to nightly for using unstable feature avoid-dev-deps
          command: rustup default nightly
      - run:
          name: Add cross compile target
          command: rustup target add thumbv7m-none-eabi
      - run:
          name: Verifies successful build for no_std target
          command: cargo clean && eval `ssh-agent` && ssh-add ~/.ssh/id_rsa && cargo build -Z avoid-dev-deps --release --no-default-features --features resp2,resp3,libm,hashbrown,alloc --target=thumbv7m-none-eabi


workflows:
  version: 2
  build:
    jobs:
      - tests-default
      - tests-indexmap
      - build-no-std
      - clippy-lint