version: 2
jobs:
  tests-default:
    docker:
      - image: cimg/rust:1.57.0
    steps:
      - checkout
      - run:
          name: Clear the cargo git cache
          command: rm -rf ~/.cargo/git/* && rm -rf ~/.cargo/registry/cache/*
      - run:
          name: Run tests with default features
          command: cargo clean && eval `ssh-agent` && ssh-add ~/.ssh/id_rsa && cargo test --release
  tests-indexmap:
    docker:
      - image: cimg/rust:1.57.0
    steps:
      - checkout
      - run:
          name: Clear the cargo git cache
          command: rm -rf ~/.cargo/git/* && rm -rf ~/.cargo/registry/cache/*
      - run:
          name: Run tests with indexmap features
          command: cargo clean && eval `ssh-agent` && ssh-add ~/.ssh/id_rsa && cargo test --release --features index-map

workflows:
  version: 2
  build:
    jobs:
      - test-default
      - test-indexmap