version: 2

jobs:
  build-docs:
    docker:
      - image: cimg/rust:1.77
    steps:
      - checkout
      - run:
          name: Install nightly
          command: rustup install nightly
      - run:
          name: Build documentation
          command: tests/doc.sh
  tests-codec:
    machine:
      image: ubuntu-2204:2022.10.2
      docker_layer_caching: true
    resource_class: medium
    environment:
      REDIS_VERSION: 7.2.4
    steps:
      - checkout
      - run:
          name: Run tests with codec features
          command: source tests/environ && tests/codec/runner.sh
  tests-bytes:
    docker:
      - image: cimg/rust:1.77
    steps:
      - checkout
      - run:
          name: Run tests with bytes features
          command: cargo test --release --features "resp2 resp3 bytes codec convert" --lib
  tests-no-bytes:
    docker:
      - image: cimg/rust:1.77
    steps:
      - checkout
      - run:
          name: Run tests without bytes or bytes_utils
          command: cargo test --release --features "resp2 resp3 convert" --lib
  tests-indexmap:
    docker:
      - image: cimg/rust:1.77
    steps:
      - checkout
      - run:
          name: Run tests with indexmap features
          command: cargo test --release --features "index-map resp2 resp3 convert" --lib
  clippy-lint:
    docker:
      - image: cimg/rust:1.77
    environment:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - checkout
      - run:
          name: Clippy
          command: cargo clippy --features "bytes convert codec std resp2 resp3" --lib --tests --benches -- -Dwarnings
  build-no-std:
    docker:
      - image: cimg/rust:1.77
    steps:
      - checkout
      - run:
          name: Switch to nightly for using unstable feature avoid-dev-deps
          command: rustup default nightly
      - run:
          name: Add cross compile target
          command: rustup target add thumbv7m-none-eabi
      - run:
          name: Verifies successful build for no_std target
          command: cargo clean && cargo build -Z avoid-dev-deps --release --no-default-features --features resp2,resp3,convert,libm,hashbrown,alloc --target=thumbv7m-none-eabi


workflows:
  version: 2
  build:
    jobs:
      - tests-bytes
      - tests-no-bytes
      - tests-codec
      - tests-indexmap
      - build-no-std
      - clippy-lint
      - build-docs