version: 2

jobs:
  build-docs:
    docker:
      - image: cimg/rust:1.77.0
    steps:
      - run:
          name: Install nightly
          command: rustup install nightly
      - run:
          name: Build documentation
          command: tests/doc.sh
  tests-codec:
    docker:
      - image: cimg/rust:1.77.0
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Run tests with codec features
          command: source tests/environ && tests/codec/runner.sh
  tests-bytes:
    docker:
      - image: cimg/rust:1.77.0
    steps:
      - checkout
      - run:
          name: Run tests with bytes features
          command: cargo test --release --features "resp2 resp3 bytes codec convert" --lib
  tests-no-bytes:
    docker:
      - image: cimg/rust:1.77.0
    steps:
      - checkout
      - run:
          name: Run tests without bytes or bytes_utils
          command: cargo test --release --features "resp2 resp3 convert" --lib
  tests-indexmap:
    docker:
      - image: cimg/rust:1.77.0
    steps:
      - checkout
      - run:
          name: Run tests with indexmap features
          command: cargo test --release --features "index-map resp2 resp3 convert" --lib
  clippy-lint:
    docker:
      - image: cimg/rust:1.77.0
    environment:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - checkout
      - run:
          name: Clippy
          command: cargo clippy --features "bytes convert codec std resp2 resp3" --lib --tests --benches -- -Dwarnings
  build-no-std:
    docker:
      - image: cimg/rust:1.77.0
    steps:
      - checkout
      - run:
          name: Switch to nightly for using unstable feature avoid-dev-deps
          command: rustup default nightly
      - run:
          name: Add cross compile target
          command: rustup target add thumbv7m-none-eabi
      - run:
          name: Verifies successful build for no_std target
          command: cargo clean && cargo build -Z avoid-dev-deps --release --no-default-features --features resp2,resp3,convert,libm,hashbrown,alloc --target=thumbv7m-none-eabi


workflows:
  version: 2
  build:
    jobs:
      - tests-bytes
      - tests-no-bytes
      - tests-codec
      - tests-indexmap
      - build-no-std
      - clippy-lint
      - build-docs